kind: Deployment
apiVersion: apps/v1
metadata:
  name: wom-ci-cd-demo
  namespace: default
  selfLink: /apis/apps/v1/namespaces/default/deployments/wom-ci-cd-demo
  uid: 652953d4-045f-4b16-9c8b-5d244038acad
  resourceVersion: '589950'
  generation: 1
  creationTimestamp: '2022-02-24T16:06:53Z'
  labels:
    appgroup: ''
    version: v1
  annotations:
    deployment.kubernetes.io/revision: '1'
    description: ''
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wom-ci-cd-demo
      version: v1
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: wom-ci-cd-demo
        version: v1
      annotations:
        metrics.alpha.kubernetes.io/custom-endpoints: '[{"api":"","path":"","port":"","names":""}]'
    spec:
      containers:
        - name: container-0
          image: 'swr.na-mexico-1.myhuaweicloud.com/huawei/wom-demo-ci-cd:latest'
          env:
            - name: PAAS_APP_NAME
              value: wom-ci-cd-demo
            - name: PAAS_NAMESPACE
              value: default
            - name: PAAS_PROJECT_ID
              value: 06a1b166c90025472f21c017afe95391
          resources:
            limits:
              cpu: 250m
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 512Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      imagePullSecrets:
        - name: default-secret
      affinity: {}
      schedulerName: default-scheduler
      tolerations:
        - key: node.kubernetes.io/not-ready
          operator: Exists
          effect: NoExecute
          tolerationSeconds: 300
        - key: node.kubernetes.io/unreachable
          operator: Exists
          effect: NoExecute
          tolerationSeconds: 300
      dnsConfig:
        options:
          - name: timeout
            value: ''
          - name: ndots
            value: '5'
          - name: single-request-reopen
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
status:
  observedGeneration: 1
  replicas: 1
  updatedReplicas: 1
  readyReplicas: 1
  availableReplicas: 1
  conditions:
    - type: Available
      status: 'True'
      lastUpdateTime: '2022-02-24T16:06:53Z'
      lastTransitionTime: '2022-02-24T16:06:53Z'
      reason: MinimumReplicasAvailable
      message: Deployment has minimum availability.
    - type: Progressing
      status: 'True'
      lastUpdateTime: '2022-02-24T16:07:16Z'
      lastTransitionTime: '2022-02-24T16:06:53Z'
      reason: NewReplicaSetAvailable
      message: ReplicaSet "wom-ci-cd-demo-6647bc6fdf" has successfully progressed.
