apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    description: ""
  creationTimestamp: "2022-02-24T16:06:53Z"
  generation: 1
  labels:
    appgroup: ""
    version: v1
  name: wom-ci-cd-demo
  namespace: default
  resourceVersion: "589950"
  selfLink: /apis/apps/v1/namespaces/default/deployments/wom-ci-cd-demo
  uid: 652953d4-045f-4b16-9c8b-5d244038acad
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: wom-ci-cd-demo
      version: v1
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      annotations:
        metrics.alpha.kubernetes.io/custom-endpoints: '[{"api":"","path":"","port":"","names":""}]'
      creationTimestamp: null
      labels:
        app: wom-ci-cd-demo
        version: v1
    spec:
      affinity: {}
      containers:
      - env:
        - name: PAAS_APP_NAME
          value: wom-ci-cd-demo
        - name: PAAS_NAMESPACE
          value: default
        - name: PAAS_PROJECT_ID
          value: 06a1b166c90025472f21c017afe95391
        image: swr.na-mexico-1.myhuaweicloud.com/huawei/wom-demo-ci-cd:latest
        imagePullPolicy: Always
        name: container-0
        resources:
          limits:
            cpu: 250m
            memory: 512Mi
          requests:
            cpu: 250m
            memory: 512Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsConfig:
        options:
        - name: timeout
          value: ""
        - name: ndots
          value: "5"
        - name: single-request-reopen
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: default-secret
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoExecute
        key: node.kubernetes.io/not-ready
        operator: Exists
        tolerationSeconds: 300
      - effect: NoExecute
        key: node.kubernetes.io/unreachable
        operator: Exists
        tolerationSeconds: 300
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
